// Codegen: data/schemas/quorum.schema.json → src/lib/types.generated.ts
//
// Invoked via `pnpm gen:types`. The Pydantic schema is the source of truth
// (regenerate with `cd backend && uv run python scripts/dump_schemas.py`).
//
// We compile each top-level `$defs` entry individually so each Pydantic
// model becomes a named interface/type alias in the output. The library's
// default behavior puts everything under a single root, which doesn't match
// the parity contract this project uses.
import { writeFileSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { compile } from "json-schema-to-typescript";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SCHEMA_PATH = resolve(__dirname, "../../data/schemas/quorum.schema.json");
const OUT_PATH = resolve(__dirname, "../src/lib/types.generated.ts");

const schema = JSON.parse(readFileSync(SCHEMA_PATH, "utf-8"));
const defs = schema.$defs ?? {};

// Pydantic emits a per-property `title` (e.g. "Source", "Title", "Url") that
// json-schema-to-typescript promotes to a named type. The result is dozens of
// phantom interfaces (Source, Title, ...) referenced but never defined. Strip
// property-level titles before compiling — keep only the top-level def title
// which names the resulting interface/type alias.
function stripPropertyTitles(node) {
  if (Array.isArray(node)) return node.map(stripPropertyTitles);
  if (node && typeof node === "object") {
    const out = {};
    for (const [k, v] of Object.entries(node)) {
      out[k] = stripPropertyTitles(v);
    }
    return out;
  }
  return node;
}
function cleanProperties(def) {
  if (!def.properties) return def;
  const cleaned = { ...def, properties: {} };
  for (const [propName, propSchema] of Object.entries(def.properties)) {
    const { title: _ignored, ...rest } = propSchema;
    cleaned.properties[propName] = stripPropertyTitles(rest);
  }
  return cleaned;
}

const banner = [
  "// DO NOT EDIT — generated by frontend/scripts/gen-types.mjs from",
  "// data/schemas/quorum.schema.json. Re-run `pnpm gen:types` after",
  "// editing backend/src/quorum/orchestrator/schemas.py.",
  "//",
  "// Source: json-schema-to-typescript",
  "",
].join("\n");

const chunks = [banner];

// Clean every def's top-level properties (and any nested $defs they re-declare).
const cleanedDefs = Object.fromEntries(
  Object.entries(defs).map(([k, v]) => [k, cleanProperties(v)]),
);

for (const [name, def] of Object.entries(cleanedDefs)) {
  // Build a self-contained subschema so $ref lookups still resolve via $defs.
  const sub = { ...def, title: name, $defs: cleanedDefs };
  const ts = await compile(sub, name, {
    bannerComment: "",
    additionalProperties: false,
    enableConstEnums: false,
    declareExternallyReferenced: false,
    unreachableDefinitions: false,
  });
  chunks.push(ts.trim());
}

writeFileSync(OUT_PATH, chunks.join("\n\n") + "\n");
console.log(`wrote ${Object.keys(defs).length} types -> ${OUT_PATH}`);
