// DO NOT EDIT — generated by frontend/scripts/gen-types.mjs from
// data/schemas/quorum.schema.json. Re-run `pnpm gen:types` after
// editing backend/src/quorum/orchestrator/schemas.py.
//
// Source: json-schema-to-typescript


export type AgentRole = "hypothesis" | "test_chooser" | "challenger" | "stewardship" | "checklist";

/**
 * A primary-source citation backing an agent's claim.
 */
export interface Citation {
  source: string;
  title?: string | null;
  url?: string | null;
  excerpt?: string | null;
}

/**
 * A single entry in the differential.
 */
export interface DiagnosisCandidate {
  name: string;
  icd10?: string | null;
  posterior: number;
  rationale: string;
  supporting_findings?: string[];
  against_findings?: string[];
  citations?: Citation[];
}

/**
 * A ranked differential diagnosis.
 */
export interface Differential {
  candidates: DiagnosisCandidate[];
  iteration?: number;
}

/**
 * A recommended next diagnostic test.
 */
export interface NextTest {
  name: string;
  rationale: string;
  estimated_cost_usd?: number | null;
  information_gain_estimate?: number | null;
  discriminates_between?: string[];
  citations?: Citation[];
}

/**
 * One utterance from one agent in a deliberation round.
 */
export interface AgentMessage {
  role: AgentRole;
  iteration: number;
  content: string;
  structured_output?:
    | Differential
    | NextTest
    | {
        [k: string]: unknown;
      }
    | null;
  citations?: Citation[];
  timestamp?: string;
  tokens_used?: number;
  cost_usd?: number;
}

/**
 * Input to the orchestrator.
 */
export interface CaseInput {
  case_id?: string | null;
  presentation: string;
  available_tests?: string[];
  budget_usd?: number | null;
  max_iterations?: number;
}

/**
 * Output of the orchestrator after deliberation concludes.
 */
export interface FinalVerdict {
  case_id?: string | null;
  final_differential: Differential;
  recommended_next_test?: NextTest | null;
  confidence: number;
  iterations_used: number;
  total_tokens: number;
  total_cost_usd: number;
  transcript: AgentMessage[];
  termination_reason: "consensus" | "budget" | "max_iterations" | "checklist_stop" | "error";
  schema_version?: number;
  is_error?: boolean;
}

/**
 * SSE event emitted during streaming deliberation.
 */
export interface StreamEvent {
  event: "agent_start" | "agent_token" | "agent_complete" | "round_complete" | "verdict" | "error";
  data: {
    [k: string]: unknown;
  };
}
